pipeline {
    environment {
        PROJECT_PATH = "/root/simple-java-maven-app"
    }
    agent any
    stages {
        stage('Build') {
            steps {
                mvn -f ${PROJECT_PATH}/pom.xml -B -DskipTests clean package
            }
        }
        stage('Run') {
            steps {
                java -jar ${PROJECT_PATH}/target/my-app.jar
            }
        }
    }
}
